### ISSUE TITLE
Resource Map Tables

### ISSUE THREAD

**Issue by esherwoo77** [tbep-tech/equity-tool#1]
Hi @BAlexSimmons ,
Very impressive and straight-forward interface. Well done. My only comment is under the mapped resources: when clicking on a potential project area polygon, the GIS feature table is overwhelming. Is it possible to restrict to the rows that have the most-relevant info for users? E.g., the underserved, overburdened, and EJissues1 row? These maybe @fawda123 questions if that's a limitation of the Mapview plugin.

**Comment by fawda123** [comment]
@BAlexSimmons the easiest way to do that is to just remove the columns from the input data to `mapview()`.  Or you could recreate in leaflet (which I did when I was troubleshooting https://github.com/tbep-tech/equity-tool/blob/013bb9a813ee1e993f01ec6e814e826764d69b48/R/dat_proc.R).
